<?php
include 'connection.php';
?>

<?php
if (isset($_POST['btnCreateQuiz'])) {
    // Assuming $connection is your database connection
    $quizname = $_POST['quizname'];
    $creationdate = date("Y-m-d H:i:s"); // Current date and time
    $teacherid = $_SESSION['teacherid']; // Assuming you have a teacher session after login

    // Insert quiz details into tblquiz
    $insertQuizQuery = "INSERT INTO tblquiz (quizname, creationdate, teacherid) VALUES ('$quizname', '$creationdate', '$teacherid')";
    mysqli_query($connection, $insertQuizQuery);

    // Retrieve the autogenerated quizid
    $quizid = mysqli_insert_id($connection);

    // Loop through each question submitted in the form
    foreach ($_POST['questions'] as $questionData) {
        $question = $questionData['question'];
        $choicea = $questionData['choicea'];
        $choiceb = $questionData['choiceb'];
        $choicec = $questionData['choicec'];
        $choiced = $questionData['choiced'];
        $correctAnswer = $questionData['correctAnswer'];

        // Insert question details into tblquestion
        $insertQuestionQuery = "INSERT INTO tblquestion (question, choicea, choiceb, choicec, choiced, quizid) VALUES ('$question', '$choicea', '$choiceb', '$choicec', '$choiced', '$quizid')";
        mysqli_query($connection, $insertQuestionQuery);

        // Update the correct answer based on the questionnum (autogenerated primary key)
        $updateAnswerQuery = "UPDATE tblquestion SET answer = '$correctAnswer' WHERE quizid = '$quizid' AND questionnum = LAST_INSERT_ID()";
        mysqli_query($connection, $updateAnswerQuery);
    }

    echo "Quiz created successfully!";
}
?>

<?php
//teacher-createLearning.php
include "connection.php";
include 'session-check.php';

checkPageAccess(['teacher']);

if (isset($_POST['btn-submit'])) {
    $lmname = $_POST['quizName'];
    $classCode = $_POST['classCode']; // Assuming this is the class code entered by the teacher
    $content = $_POST['textarea']; // Assuming this is the content entered by the teacher

    // Retrieve classid based on the provided class code
    $getClassIdQuery = "SELECT classid FROM tblclass WHERE classid = '$classCode'";
    $resultClassId = mysqli_query($connection, $getClassIdQuery);

    if ($resultClassId) {
        if (mysqli_num_rows($resultClassId) > 0) {
            $classData = mysqli_fetch_assoc($resultClassId);
            $classid = $classData['classid'];

            $teacherid = $_SESSION['teacherid'];
            $creationdate = date("Y-m-d H:i:s");

            // Insert learning material details into tbllm
            $insertLMQuery = "INSERT INTO tbllm (teacherid, classid, creationdate) VALUES ('$teacherid', '$classid', '$creationdate')";

            if (mysqli_query($connection, $insertLMQuery)) {
                // Retrieving the autogenerated lmid
                $lmid = mysqli_insert_id($connection);

                // Insert learning material content into tblcontent
                $insertContentQuery = "INSERT INTO tblcontent (lmid, lmname, description, video) VALUES (?, ?, ?, '')";

                // Prepare the statement
                $stmt = mysqli_prepare($connection, $insertContentQuery);

                // Bind parameters
                mysqli_stmt_bind_param($stmt, "iss", $lmid, $lmname, $content);

                // Execute the statement
                if (mysqli_stmt_execute($stmt)) {
                    echo "Learning material created successfully!";
                } else {
                    echo "Error inserting content: " . mysqli_stmt_error($stmt);
                }

                // Close the statement
                mysqli_stmt_close($stmt);
            } else {
                echo "Error inserting learning material: " . mysqli_error($connection);
            }
        } else {
            echo "No rows found for the class code: $classCode";
        }
    } else {
        echo "Error executing the query: " . mysqli_error($connection);
    }
}
?>


<?php
//teacher-createClassroom.php
include "connection.php";
include "session-check.php";

// Check if the form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['btn-submit'])) {
    // Get the classname from the form
    $classname = $_POST["quizName"];

    // Check if teacherid is set in the session
    if (isset($_SESSION["teacherid"])) {
        $teacherid = $_SESSION["teacherid"];

        // Insert data into tblclass
        $sql_insert_class = "INSERT INTO tblclass (teacherid, classname) VALUES ('$teacherid', '$classname')";

        if (mysqli_query($connection, $sql_insert_class)) {
            $classid = mysqli_insert_id($connection); // Get the last inserted ID

            // Echo success message
            echo "Your class has been created, and Your Class Code is " . $classid;
        } else {
            // Echo an error message if the query fails
            echo "Error: " . mysqli_error($connection);
        }
    } else {
        echo "Error: Teacher ID not found in session.";
    }
}

mysqli_close($connection);
?>

<?php
//session-check.php
session_start();

function checkSession() {
    // Check if the user is logged in
    if (!isset($_SESSION['role'])) {
        header("Location: user-login.php"); // Redirect to the login page if not logged in
        exit();
    }

    // Check the user role
    $role = $_SESSION['role'];

    return $role;
}

function checkPageAccess($allowedRoles) {
    $role = checkSession();

    // Check if the user has the correct role for the page
    if (!in_array($role, $allowedRoles)) {
        echo "Error: You Have No Access To This Page.";
        exit();
    }
}
?>


<!-- teacher cretae quiz -->

<?php
include "connection.php";
include 'session-check.php';

checkPageAccess(['teacher']);

if (isset($_POST['btn-submit'])) {
    $quizname = $_POST['quizName'];
    $classid = $_POST['classCode'];
    $teacherid = $_SESSION['teacherid'];
    $creationdate = date("Y-m-d H:i:s");

    // Insert quiz details into tblquiz
    $insertQuizQuery = "INSERT INTO tblquiz (teacherid, classid, quizname, creationdate) VALUES ('$teacherid', '$classid', '$quizname', '$creationdate')";
    mysqli_query($connection, $insertQuizQuery);

    // Retrieve the autogenerated quizid
    $quizid = mysqli_insert_id($connection);

    // Loop through each question submitted in the form
    $questionIndex = 1;
    while (isset($_POST["question$questionIndex"])) {
        $question = $_POST["question$questionIndex"];
        $choicea = $_POST["option$questionIndex-A"];
        $choiceb = $_POST["option$questionIndex-B"];
        $choicec = $_POST["option$questionIndex-C"];
        $choiced = $_POST["option$questionIndex-D"];
        $answer = $_POST["correctAnswer$questionIndex"];

        // Insert question details into tblquestion with the quizid
        $insertQuestionQuery = "INSERT INTO tblquestion (quizid, question, choicea, choiceb, choicec, choiced, answer) VALUES ('$quizid', '$question', '$choicea', '$choiceb', '$choicec', '$choiced', '$answer')";
        mysqli_query($connection, $insertQuestionQuery);

        $questionIndex++;
    }

    echo "Quiz created successfully!";
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Quiz</title>

    <link rel="stylesheet" href="../css/teacher-createQuiz.css" />
    <link rel="stylesheet" href="../css/nav.css" />
    <link rel="stylesheet" href="../css/footer.css" />

    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Lemon&display=swap" rel="stylesheet" />
</head>
<script src="../javascript/createQuiz.js"></script>

<body>
    <!-- content -->
    <div class="main-wrapper">
        <h1>Create A Quiz</h1>
        <div class="input-area">
            <form action="#" method="post">
                <label for="quizName">Quiz Name</label>
                <input type="text" name="quizName" id="quizName" placeholder="Enter Quiz Name" required />
                <label for="classCode">Class Code</label>
                <input type="text" name="classCode" id="classCode" placeholder="Enter Class Code" required />
                <div id="questions">
                    <div class="question">
                        <label for="question1">Question 1</label>
                        <input type="text" name="question1" id="question1" placeholder="Enter The Question" required />

                        <div class="options">
                            <div class="option">
                                <label for="option1-A">Option A</label>
                                <input type="text" name="option1-A" id="option1-A" placeholder="Enter Option 1"
                                    required />
                            </div>
                            <div class="option">
                                <label for="option1-B">Option B</label>
                                <input type="text" name="option1-B" id="option1-B" placeholder="Enter Option 2"
                                    required />
                            </div>
                            <div class="option">
                                <label for="option1-C">Option C</label>
                                <input type="text" name="option1-C" id="option1-C" placeholder="Enter Option 3"
                                    required />
                            </div>
                            <div class="option">
                                <label for="option1-D">Option D</label>
                                <input type="text" name="option1-D" id="option1-D" placeholder="Enter Option 4"
                                    required />
                            </div>
                        </div>

                        <label for="correctAnswer1">Correct Answer</label>
                        <select name="correctAnswer1" id="correctAnswer1">
                            <option value="option1-A">Option A</option>
                            <option value="option1-B">Option B</option>
                            <option value="option1-C">Option C</option>
                            <option value="option1-D">Option D</option>
                        </select>
                        <div class="delete-icon" data-tooltip="Delete Question">
                            <a href="">
                                <i class="bx bx-message-square-x"></i>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="btn">
                    <button type="button" id="addQuestion">
                        Add Question
                    </button>
                    <a href="">
                        <button type="submit" class="btn-submit" name="btn-submit">Create Quiz</button>
                    </a>
                </div>
            </form>
        </div>
    </div>
    <!-- copyright part -->
    <div class="copyright">
        <p>© 2024 BreezeQuiz. All rights reserved.</p>
    </div>
</body>

</html>