<?php
include 'connection.php';
?>

<?php
if (isset($_POST['btnCreateQuiz'])) {
    // Assuming $connection is your database connection
    $quizname = $_POST['quizname'];
    $creationdate = date("Y-m-d H:i:s"); // Current date and time
    $teacherid = $_SESSION['teacherid']; // Assuming you have a teacher session after login

    // Insert quiz details into tblquiz
    $insertQuizQuery = "INSERT INTO tblquiz (quizname, creationdate, teacherid) VALUES ('$quizname', '$creationdate', '$teacherid')";
    mysqli_query($connection, $insertQuizQuery);

    // Retrieve the autogenerated quizid
    $quizid = mysqli_insert_id($connection);

    // Loop through each question submitted in the form
    foreach ($_POST['questions'] as $questionData) {
        $question = $questionData['question'];
        $choicea = $questionData['choicea'];
        $choiceb = $questionData['choiceb'];
        $choicec = $questionData['choicec'];
        $choiced = $questionData['choiced'];
        $correctAnswer = $questionData['correctAnswer'];

        // Insert question details into tblquestion
        $insertQuestionQuery = "INSERT INTO tblquestion (question, choicea, choiceb, choicec, choiced, quizid) VALUES ('$question', '$choicea', '$choiceb', '$choicec', '$choiced', '$quizid')";
        mysqli_query($connection, $insertQuestionQuery);

        // Update the correct answer based on the questionnum (autogenerated primary key)
        $updateAnswerQuery = "UPDATE tblquestion SET answer = '$correctAnswer' WHERE quizid = '$quizid' AND questionnum = LAST_INSERT_ID()";
        mysqli_query($connection, $updateAnswerQuery);
    }

    echo "Quiz created successfully!";
}
?>

<?php
//teacher-createLearning.php
include "connection.php";
include 'session-check.php';

checkPageAccess(['teacher']);

if (isset($_POST['btn-submit'])) {
    $lmname = $_POST['quizName'];
    $classCode = $_POST['classCode']; // Assuming this is the class code entered by the teacher
    $content = $_POST['textarea']; // Assuming this is the content entered by the teacher

    // Retrieve classid based on the provided class code
    $getClassIdQuery = "SELECT classid FROM tblclass WHERE classid = '$classCode'";
    $resultClassId = mysqli_query($connection, $getClassIdQuery);

    if ($resultClassId) {
        if (mysqli_num_rows($resultClassId) > 0) {
            $classData = mysqli_fetch_assoc($resultClassId);
            $classid = $classData['classid'];

            $teacherid = $_SESSION['teacherid'];
            $creationdate = date("Y-m-d H:i:s");

            // Insert learning material details into tbllm
            $insertLMQuery = "INSERT INTO tbllm (teacherid, classid, creationdate) VALUES ('$teacherid', '$classid', '$creationdate')";

            if (mysqli_query($connection, $insertLMQuery)) {
                // Retrieving the autogenerated lmid
                $lmid = mysqli_insert_id($connection);

                // Insert learning material content into tblcontent
                $insertContentQuery = "INSERT INTO tblcontent (lmid, lmname, description, video) VALUES (?, ?, ?, '')";

                // Prepare the statement
                $stmt = mysqli_prepare($connection, $insertContentQuery);

                // Bind parameters
                mysqli_stmt_bind_param($stmt, "iss", $lmid, $lmname, $content);

                // Execute the statement
                if (mysqli_stmt_execute($stmt)) {
                    echo "Learning material created successfully!";
                } else {
                    echo "Error inserting content: " . mysqli_stmt_error($stmt);
                }

                // Close the statement
                mysqli_stmt_close($stmt);
            } else {
                echo "Error inserting learning material: " . mysqli_error($connection);
            }
        } else {
            echo "No rows found for the class code: $classCode";
        }
    } else {
        echo "Error executing the query: " . mysqli_error($connection);
    }
}
?>


<?php
//teacher-createClassroom.php
include "connection.php";
include "session-check.php";

// Check if the form is submitted
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['btn-submit'])) {
    // Get the classname from the form
    $classname = $_POST["quizName"];

    // Check if teacherid is set in the session
    if (isset($_SESSION["teacherid"])) {
        $teacherid = $_SESSION["teacherid"];

        // Insert data into tblclass
        $sql_insert_class = "INSERT INTO tblclass (teacherid, classname) VALUES ('$teacherid', '$classname')";

        if (mysqli_query($connection, $sql_insert_class)) {
            $classid = mysqli_insert_id($connection); // Get the last inserted ID

            // Echo success message
            echo "Your class has been created, and Your Class Code is " . $classid;
        } else {
            // Echo an error message if the query fails
            echo "Error: " . mysqli_error($connection);
        }
    } else {
        echo "Error: Teacher ID not found in session.";
    }
}

mysqli_close($connection);
?>

<?php
//session-check.php
session_start();

function checkSession() {
    // Check if the user is logged in
    if (!isset($_SESSION['role'])) {
        header("Location: user-login.php"); // Redirect to the login page if not logged in
        exit();
    }

    // Check the user role
    $role = $_SESSION['role'];

    return $role;
}

function checkPageAccess($allowedRoles) {
    $role = checkSession();

    // Check if the user has the correct role for the page
    if (!in_array($role, $allowedRoles)) {
        echo "Error: You Have No Access To This Page.";
        exit();
    }
}
?>