<?php
include 'connection.php';
?>

<?php
if (isset($_POST['btnCreateQuiz'])) {
    // Assuming $connection is your database connection
    $quizname = $_POST['quizname'];
    $creationdate = date("Y-m-d H:i:s"); // Current date and time
    $teacherid = $_SESSION['teacherid']; // Assuming you have a teacher session after login

    // Insert quiz details into tblquiz
    $insertQuizQuery = "INSERT INTO tblquiz (quizname, creationdate, teacherid) VALUES ('$quizname', '$creationdate', '$teacherid')";
    mysqli_query($connection, $insertQuizQuery);

    // Retrieve the autogenerated quizid
    $quizid = mysqli_insert_id($connection);

    // Loop through each question submitted in the form
    foreach ($_POST['questions'] as $questionData) {
        $question = $questionData['question'];
        $choicea = $questionData['choicea'];
        $choiceb = $questionData['choiceb'];
        $choicec = $questionData['choicec'];
        $choiced = $questionData['choiced'];
        $correctAnswer = $questionData['correctAnswer'];

        // Insert question details into tblquestion
        $insertQuestionQuery = "INSERT INTO tblquestion (question, choicea, choiceb, choicec, choiced, quizid) VALUES ('$question', '$choicea', '$choiceb', '$choicec', '$choiced', '$quizid')";
        mysqli_query($connection, $insertQuestionQuery);

        // Update the correct answer based on the questionnum (autogenerated primary key)
        $updateAnswerQuery = "UPDATE tblquestion SET answer = '$correctAnswer' WHERE quizid = '$quizid' AND questionnum = LAST_INSERT_ID()";
        mysqli_query($connection, $updateAnswerQuery);
    }

    echo "Quiz created successfully!";
}
?>

